headersOrigin = "inline"
redirectsOrigin = "inline"

[build]
edge_functions = "F:\\AI-Native IP\\frontend\\netlify\\edge-functions"
publish = "F:\\AI-Native IP\\frontend\\.next"
publishOrigin = "config"
commandOrigin = "config"
base = "F:\\AI-Native IP\\frontend"
command = "npm run build"

[build.environment]
NODE_VERSION = "20"
NEXT_TELEMETRY_DISABLED = "1"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[edge_functions]]
function = "api-proxy"
path = "/api/*"

[dev]
command = "npm run dev"
targetPort = 3000.0
publish = ".next"

[images]
remote_images = ["^(?:https:\\/\\/ai-native-ip-production\\.up\\.railway\\.app(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"]

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"
pinned_version = "5"

[plugins.inputs]

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/api/*"
to = "https://ai-native-ip-production.up.railway.app/api/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/health"
to = "https://ai-native-ip-production.up.railway.app/health"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]