-- 为 IP 账号体系补充字段（幂等）
-- 解决创建 IP 时因列不存在导致的提交失败。

ALTER TABLE ip ADD COLUMN IF NOT EXISTS nickname VARCHAR(100);
ALTER TABLE ip ADD COLUMN IF NOT EXISTS bio VARCHAR(500);

ALTER TABLE ip ADD COLUMN IF NOT EXISTS monetization_model VARCHAR(50);
ALTER TABLE ip ADD COLUMN IF NOT EXISTS target_audience VARCHAR(255);
ALTER TABLE ip ADD COLUMN IF NOT EXISTS content_direction VARCHAR(255);
ALTER TABLE ip ADD COLUMN IF NOT EXISTS unique_value_prop VARCHAR(500);

ALTER TABLE ip ADD COLUMN IF NOT EXISTS expertise VARCHAR(255);
ALTER TABLE ip ADD COLUMN IF NOT EXISTS passion VARCHAR(255);
ALTER TABLE ip ADD COLUMN IF NOT EXISTS market_demand VARCHAR(255);

ALTER TABLE ip ADD COLUMN IF NOT EXISTS product_service VARCHAR(255);
ALTER TABLE ip ADD COLUMN IF NOT EXISTS price_range VARCHAR(100);
ALTER TABLE ip ADD COLUMN IF NOT EXISTS repurchase_rate VARCHAR(50);
